### PR TITLE
Fix schemas caching problem

### PR DESCRIPTION
**Pull request by sparrovv**
@chuwy I've noticed that caching doesn't work as expected. It was keep adding new entries and not reusing already existing ones, when I was passing schemas as strings. 

Please refer to the commit messages for more information.

### CODE REVIEW

**Comment by snowplowcla** [comment]
@sparrovv has signed the Software Grant and Corporate Contributor License Agreement

**Review by chuwy — APPROVED** [review]
Thank you very much @sparrovv! This looks great.

**Comment by sparrovv** [comment]
Cool, when can I expect that to be merged? Or is there anything else I should do?

**Comment by chuwy** [comment]
Hey @sparrovv! Nothing required from you (though squashing commits would be nice, but optional). No ETA, but having small scope for possible release and important fixes - we may want to publish quick bugfix release.

**Comment by pvdb** [comment]
Can we please change:

```ruby
class SchemaVer < Struct.new(:model, :revision, :addition)
  ...
end
```

to:

```ruby
SchemaVer = Struct.new(:model, :revision, :addition) do
  ...
end
```

_(and the same for `SchemaKey`)_

Idiomatic Ruby #FTW!

**Comment by pvdb** [comment]
@chuwy - do you have an ETA for the bugfix release?

**Review by pvdb — COMMENTED** [review]
Awesome clarification of the problem and the fix, @sparrovv :thumbsup:

**Comment by sparrovv** [comment]
Hey @chuwy are you going to maintain this project? There's no much movement on those fixes?

**Comment by alexanderdean** [comment]
Hey @sparrovv - it's on our radar, but we don't have a firm date on this release yet.

**Comment by oguzhanunlu** [comment]
Cherry-picked to #14 . Closing.

**Pull request closed without merging**
